### PR TITLE
Adelaide scenic flights, RAAF TERMA doc

### PR DESCRIPTION
**Pull request by mattkelly4**
- Add notes to Adelaide AD/TCU for handling coastal flights
- Add note to Adelaide AD for referencing taxiways
- Add reference to military pages for RAAF TERMA doc (providing charts for military procedures like YPED STARs, etc)

### CODE REVIEW

**Review by alexd-332 — APPROVED** [review]
Looks good. Maybe worth some additional thought towards how we wanna handle these sorts of transits. IRL AD ADC own no airspace (I'm halfway through fixing that in a separate PR, as well as for some other towers). But aircraft are transferred to AD ADC for them to visually separate with arrivals and departures (which I agree should be done by ADC on vatsim too, especially since we have auto-release on at YPAD). But need to have a think about what actual Sep standard we can prescribe for ADC to use. Can be part of a more big-picture think about how we actually apply Pseudo-visual separation on vatsim.

Cause if we wanna go with Pseudo-visual Sep, should be done by ADC.

But if we wanna go with applying some form of a 3nm standard, then should be done by TCU with a temporary cancellation of auto-release.

**Comment by mattkelly4** [comment]
> Looks good. Maybe worth some additional thought towards how we wanna handle these sorts of transits. IRL AD ADC own no airspace (I'm halfway through fixing that in a separate PR, as well as for some other towers). But aircraft are transferred to AD ADC for them to visually separate with arrivals and departures (which I agree should be done by ADC on vatsim too, especially since we have auto-release on at YPAD). But need to have a think about what actual Sep standard we can prescribe for ADC to use. Can be part of a more big-picture think about how we actually apply Pseudo-visual separation on vatsim.
> 
> Cause if we wanna go with Pseudo-visual Sep, should be done by ADC.
> 
> But if we wanna go with applying some form of a 3nm standard, then should be done by TCU with a temporary cancellation of auto-release.

Yeah sounds good.  I was working off the current arrangement of ADC owning SFC-015 but more than happy to adjust as required.  I think what you've suggested sounds good and I'd support a form of visual sep being maintained by the tower.  I reckon that we encourage tower controllers to use towerview in their flight sim and fall back on using vatsys if they don't have one.

**Comment by alexd-332** [comment]
> > Looks good. Maybe worth some additional thought towards how we wanna handle these sorts of transits. IRL AD ADC own no airspace (I'm halfway through fixing that in a separate PR, as well as for some other towers). But aircraft are transferred to AD ADC for them to visually separate with arrivals and departures (which I agree should be done by ADC on vatsim too, especially since we have auto-release on at YPAD). But need to have a think about what actual Sep standard we can prescribe for ADC to use. Can be part of a more big-picture think about how we actually apply Pseudo-visual separation on vatsim.
> > 
> > Cause if we wanna go with Pseudo-visual Sep, should be done by ADC.
> > 
> > But if we wanna go with applying some form of a 3nm standard, then should be done by TCU with a temporary cancellation of auto-release.
> 
> Yeah sounds good.  I was working off the current arrangement of ADC owning SFC-015 but more than happy to adjust as required.  I think what you've suggested sounds good and I'd support a form of visual sep being maintained by the tower.  I reckon that we encourage tower controllers to use towerview in their flight sim and fall back on using vatsys if they don't have one.

Yeah I'm all for some sort of visual separation existing, but would be great if we could translate that in to a practical standard for people to use on vatsys. Something like 1nm lateral, 500ft vertical, VMC, within 5nm of the ARP. Or along those lines

**Comment by mattkelly4** [comment]
Deleted PR - incorporated into Alex's PR

**Pull request closed without merging**
