### PR TITLE
Fix Controller Skills ordering

### PR DESCRIPTION
**Pull request by mattkelly4**
Renamed files with capitalisation back to lowercase and updated references.

### CODE REVIEW

**Review by alexd-332 — DISMISSED** [review]
What are the odds it absolutely goes to shit again lol

**Comment by mattkelly4** [comment]
> What are the odds it absolutely goes to shit again lol

Review dismissed within a minute of approving, I think there's your answer haha

**Comment by alexd-332** [comment]
> > What are the odds it absolutely goes to shit again lol
> 
> Review dismissed within a minute of approving, I think there's your answer haha

Haha it's so cooked hey. Idk if you saw in Tyler and I's pulls as well but we would fix the order, and would show completely normally and perfectly on the local server, then when it got merged it would be a complete disaster

**Comment by tylerthetiletiler** [comment]
wHAT iVE Done DOesn"t seEEm to HaVE fiXED ANytHIng. HEReS an APPpROVaAL

**Review by tylerthetiletiler — APPROVED** [review]

**Review by LeGiraffe — APPROVED** [review]

**Review by alexd-332 — APPROVED** [review]

**Pull request merged**
