### PR TITLE
Military pages & more

### PR DESCRIPTION
**Pull request by alphadelta332**
## Summary
Addition of Military Local Instructions at YCIN, YPLM, YBSG and YPWR, plus other miscellaneous changes

## Changes
**Fixes**:
- Multiple miscellaneous coordination example fixes
- LUFTHANSA capitalisation in Callsigns page
- East Sale abbreviation ESL -> ES in ELW and YWE pages
- Amberley abbreviation AM -> AMB in AMB, OK, INL pages
- Multiple typos

**Changes**:
- Surveillance standards **no longer permitted** to be used at Class D Towers
- YWLM callsigns changed from Willy -> **Williamtown**
- Recommended History trails for Enroute controllers changed from **OFF** to **9**
- Recommended History trails for TCU and ADC controllers changed from **OFF** to **5**
- RTCC map now recommended for TCU controllers in lieu of waypoint names map

**Additions**:
- CIN ADC and TCU page
- Coordination Requirements from TRT to CIN ADC/TCU
- LM ADC and TCU page
- Coordination Requirements from OLW to LM ADC/TCU
- SG ADC and TCU page
- Coordination Requirements from ISA to SG ADC/TCU
- WR ADC page
- Coordination Requirements from ASP to WR ADC
- Notes in Procedural Tower pages and Class D Tower Sep Standards page about using coordination for surveillance separation
- BATIK Callsign in Callsigns page
- 2 minute departure Procedural standard
- New High/Low position available in **WLM TCU**
- New North/South position available in **NWWW TCU**

### CODE REVIEW

**Comment by mattkelly4** [comment]
Looks awesome. Just to clarify, have the YWLM control position *callsigns* been changed to the full 'Williamtown'? Last I was there it was Willy but that was a few years ago, not sure if it has changed recently. Also with the new high/low positions, is anything required from an AIS perspective to make everything match up?

**Comment by alphadelta332** [comment]
> Looks awesome. Just to clarify, have the YWLM control position *callsigns* been changed to the full 'Williamtown'? Last I was there it was Willy but that was a few years ago, not sure if it has changed recently. Also with the new high/low positions, is anything required from an AIS perspective to make everything match up?

Williamtown change was going off what Brett was saying in discord the other day, but maybe I got confused and it's only Williamtown for the ATIS, Willy for everything else?

High low positions already in the AIS system 👍

**Review by tylerthetiletiler — DISMISSED** [review]

**Comment by mattkelly4** [comment]
> > Looks awesome. Just to clarify, have the YWLM control position _callsigns_ been changed to the full 'Williamtown'? Last I was there it was Willy but that was a few years ago, not sure if it has changed recently. Also with the new high/low positions, is anything required from an AIS perspective to make everything match up?
> 
> Williamtown change was going off what Brett was saying in discord the other day, but maybe I got confused and it's only Williamtown for the ATIS, Willy for everything else?
> 
> High low positions already in the AIS system 👍

Yeah cool. Looks like it might just be the ATIS, ERSA still has the control position callsigns using Willy.
image

**Comment by alphadelta332** [comment]
> > > Looks awesome. Just to clarify, have the YWLM control position _callsigns_ been changed to the full 'Williamtown'? Last I was there it was Willy but that was a few years ago, not sure if it has changed recently. Also with the new high/low positions, is anything required from an AIS perspective to make everything match up?
> > 
> > Williamtown change was going off what Brett was saying in discord the other day, but maybe I got confused and it's only Williamtown for the ATIS, Willy for everything else?
> > 
> > High low positions already in the AIS system 👍
> 
> Yeah cool. Looks like it might just be the ATIS, ERSA still has the control position callsigns using Willy.
> image
> 

Yep good find, fixed now

**Review by tylerthetiletiler — APPROVED** [review]

**Review by mattkelly4 — APPROVED** [review]

**Review by JoshuaMicallefYBSU — APPROVED** [review]

**Pull request merged**
