### PR TITLE
misc fixes

### PR DESCRIPTION
**Pull request by alexdiederich**

### CODE REVIEW

**Review by chrisg06 — COMMENTED** [review]
Looks good. I'll wait for either Zach or Matt to review as well.

**Comment by mattkelly4** [comment]
With the `military` menu heading, is the idea that we'd have a single heading for each aerodrome and have both AD and TMA stuff on the same page?  Or would these aerodromes be better sorted under the existing Aerodrome/TMA headings?

**Comment by alexdiederich** [comment]
> With the `military` menu heading, is the idea that we'd have a single heading for each aerodrome and have both AD and TMA stuff on the same page? Or would these aerodromes be better sorted under the existing Aerodrome/TMA headings?

not sure, just sort of put it there as a placeholder. maybe the raaf guys can get a bit of a feel when they start working on it as to how it'd be best laid out

**Review by mattkelly4 — APPROVED** [review]
No objections

**Review by zachbf — APPROVED** [review]

**Pull request merged**
