### PR TITLE
Remove unnecessary oceanic sep standards

### PR DESCRIPTION
**Pull request by alexdiederich**
delete mach number technique
delete lat sep diagrams
add explanation of how to use conflict area tool

### CODE REVIEW

**Comment by zachbf** [comment]
So just confirming, these procedural techniques are not used IRL anymore?

**Comment by alexdiederich** [comment]
> So just confirming, these procedural techniques are not used IRL anymore?

not sure about oceanic, they might be used, but its a pretty complex way to squeeze aircraft in just a tiny bit closer, when separating using a 10min SRP longitudinally, and 5in/5out with conflict area tool laterally, is more than adequate

**Review by tylerthetiletiler — APPROVED** [review]
app

**Comment by zachbf** [comment]
i'll approve and merge for now, but will discuss with @mattkelly4 further and in our final wider review of content.

**Pull request merged**
