### PR TITLE
placeholders, proc towers, new stuff

### PR DESCRIPTION
**Pull request by alexd-332**
HUO
- minor formatting fix

TAS TCU
- adjusted coord to match HUO

BN TCU
- adjusted coord to match INL

general
- created all placeholders
- fixed to internal formatting, standardised
- removed taxi and dep calls for towers
- ensured all placeholders had "Reserved" as text

coord
- added NFR
- removed taxi call
- minor changes to coord rules

Oceanic coord
- moved to coord page

LSALT page
- new

vatsys setup
- new

Todo list
- updated

Abbreviations
- added

### CODE REVIEW

**Review by tylerthetiletiler — APPROVED** [review]

**Review by zkgell — APPROVED** [review]

**Review by tylerthetiletiler — DISMISSED** [review]

**Review by LeGiraffe — COMMENTED** [review]
With regards to AY Coord, did we want to reverse the ELW(BLA) as a technicality... to BLA(ELW)

**Comment by alexd-332** [comment]
> With regards to AY Coord, did we want to reverse the ELW(BLA) as a technicality... to BLA(ELW)

I suppose we can, but would require changes to lots of other pages too. Not fussed

**Review by LeGiraffe — APPROVED** [review]

**Comment by LeGiraffe** [comment]
> > With regards to AY Coord, did we want to reverse the ELW(BLA) as a technicality... to BLA(ELW)
> 
> I suppose we can, but would require changes to lots of other pages too. Not fussed.
> 
> Can maybe save it for another pull request if we decide to

How's it quoted in the ENR LOAs? Does it use the group name as opposed to sector? For example; Albury Tower will coordinated XYZ with Monaro... or Albury Tower will coordinated with X sector?

**Comment by alexd-332** [comment]
> > > With regards to AY Coord, did we want to reverse the ELW(BLA) as a technicality... to BLA(ELW)
> > 
> > I suppose we can, but would require changes to lots of other pages too. Not fussed.
> > 
> > Can maybe save it for another pull request if we decide to
> 
> How's it quoted in the ENR LOAs? Does it use the group name as opposed to sector? For example; Albury Tower will coordinated XYZ with Monaro... or Albury Tower will coordinated with X sector?

The documents are named "Standard coordination procedures between Albury Tower and Monaro", but then in the docs themselves it only refers to HUM and OVN individually. So idk lol.

**Review by chrisg06 — APPROVED** [review]

**Review by chrisg06 — APPROVED** [review]

**Comment by LeGiraffe** [comment]
> > > > With regards to AY Coord, did we want to reverse the ELW(BLA) as a technicality... to BLA(ELW)
> > > 
> > > I suppose we can, but would require changes to lots of other pages too. Not fussed.
> > > 
> > > Can maybe save it for another pull request if we decide to
> > 
> > How's it quoted in the ENR LOAs? Does it use the group name as opposed to sector? For example; Albury Tower will coordinated XYZ with Monaro... or Albury Tower will coordinated with X sector?
> 
> The documents are named "Standard coordination procedures between Albury Tower and Monaro", but then in the docs themselves it only refers to HUM and OVN individually. So idk lol. 

If it's a big job to change & that's how you've done it through all, no problem & don't worry.

Just though format Sector(Parent Sector) could work... but splitting hairs at this point. I have no objections to how it is now.

**Review by LeGiraffe — APPROVED** [review]

**Review by zkgell — APPROVED** [review]

**Pull request merged**
